language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - iojs
addons:
  code_climate:
    repo_token:
      secure: IgtC/fOiI7cwqrvRv/uMqw556xf7uwVrRL65j/Scy2evgV7nFbn3+wr7JSVlb6RHTM0qAhpWMBzxZdLSxHH3LKvhu3cj/e+QhjyzvQx9lpu/7u3rPZ24HpQX0iBvrKU0rJOhOqsLnnpqfHDUVfwcjWstZRxOj8k9P/MbfqPM0/c=
after_script:
  - npm run coverage | codeclimate
